### ISSUE TITLE
Warning: Link: Support for defaultProps will be removed from function components in a future major release.

### ISSUE THREAD

**Issue by teplostanski** [sindresorhus/ink-link#16]
I see this message in the console. React 18.3.1

```sh
Warning: Link: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Link (file:///data/data/com.termux/files/home/imonline/node_modules/ink-link/dist/index.js:28:43)
    at ink-text
    at Text (file:///data/data/com.termux/files/home/imonline/node_modules/ink/build/components/Text.js:7:32)
    at ink-box
    at file:///data/data/com.termux/files/home/imonline/node_modules/ink/build/components/Box.js:5:27
    at ink-box
    at file:///data/data/com.termux/files/home/imonline/node_modules/ink/build/components/Box.js:5:27
    at Copyright (file:///data/data/com.termux/files/home/imonline/dist/components/copyright.js:25:29)
    at App (file:///data/data/com.termux/files/home/imonline/node_modules/ink/build/components/App.js:17:16)
```

**Comment by teplostanski** [comment]
PR[ #17 ](https://github.com/sindresorhus/ink-link/pull/17)
